//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisaton
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int INN { get; set; }
        public string LegalAddress { get; set; }
        public string ActualAddress { get; set; }
    }
}
